import { defineConfig } from "tsup"

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "components/accordion": "src/components/accordion.ts",
    "components/alert": "src/components/alert.ts",
    "components/alert-dialog": "src/components/alert-dialog.ts",
    "components/aspect-ratio": "src/components/aspect-ratio.ts",
    "components/avatar": "src/components/avatar.ts",
    "components/badge": "src/components/badge.ts",
    "components/breadcrumb": "src/components/breadcrumb.ts",
    "components/button": "src/components/button.ts",
    "components/button-group": "src/components/button-group.ts",
    "components/calendar": "src/components/calendar.ts",
    "components/card": "src/components/card.ts",
    "components/carousel": "src/components/carousel.ts",
    "components/chart": "src/components/chart.ts",
    "components/checkbox": "src/components/checkbox.ts",
    "components/collapsible": "src/components/collapsible.ts",
    "components/combobox": "src/components/combobox.ts",
    "components/command": "src/components/command.ts",
    "components/context-menu": "src/components/context-menu.ts",
    "components/direction": "src/components/direction.ts",
    "components/dialog": "src/components/dialog.ts",
    "components/drawer": "src/components/drawer.ts",
    "components/dropdown-menu": "src/components/dropdown-menu.ts",
    "components/empty": "src/components/empty.ts",
    "components/field": "src/components/field.ts",
    "components/form": "src/components/form.ts",
    "components/hover-card": "src/components/hover-card.ts",
    "components/input": "src/components/input.ts",
    "components/input-group": "src/components/input-group.ts",
    "components/input-otp": "src/components/input-otp.ts",
    "components/item": "src/components/item.ts",
    "components/kbd": "src/components/kbd.ts",
    "components/label": "src/components/label.ts",
    "components/menubar": "src/components/menubar.ts",
    "components/navigation-menu": "src/components/navigation-menu.ts",
    "components/native-select": "src/components/native-select.ts",
    "components/pagination": "src/components/pagination.ts",
    "components/popover": "src/components/popover.ts",
    "components/progress": "src/components/progress.ts",
    "components/radio-group": "src/components/radio-group.ts",
    "components/resizable": "src/components/resizable.ts",
    "components/scroll-area": "src/components/scroll-area.ts",
    "components/select": "src/components/select.ts",
    "components/separator": "src/components/separator.ts",
    "components/sheet": "src/components/sheet.ts",
    "components/sidebar": "src/components/sidebar.ts",
    "components/skeleton": "src/components/skeleton.ts",
    "components/slider": "src/components/slider.ts",
    "components/sonner": "src/components/sonner.ts",
    "components/spinner": "src/components/spinner.ts",
    "components/switch": "src/components/switch.ts",
    "components/table": "src/components/table.ts",
    "components/tabs": "src/components/tabs.ts",
    "components/textarea": "src/components/textarea.ts",
    "components/toggle": "src/components/toggle.ts",
    "components/toggle-group": "src/components/toggle-group.ts",
    "components/tooltip": "src/components/tooltip.ts",
    "components/display/avatar": "src/components/display/avatar.tsx",
    "components/display/badge": "src/components/display/badge.tsx",
    "components/display/chart": "src/components/display/chart.tsx",
    "components/display/empty": "src/components/display/empty.tsx",
    "components/display/kbd": "src/components/display/kbd.tsx",
    "components/display/skeleton": "src/components/display/skeleton.tsx",
    "components/display/table": "src/components/display/table.tsx",
    "components/feedback/alert": "src/components/feedback/alert.tsx",
    "components/feedback/progress": "src/components/feedback/progress.tsx",
    "components/feedback/sonner": "src/components/feedback/sonner.tsx",
    "components/feedback/spinner": "src/components/feedback/spinner.tsx",
    "components/forms/calendar": "src/components/forms/calendar.tsx",
    "components/forms/combobox": "src/components/forms/combobox.tsx",
    "components/forms/field": "src/components/forms/field.tsx",
    "components/forms/form": "src/components/forms/form.tsx",
    "components/forms/input-group": "src/components/forms/input-group.tsx",
    "components/forms/input-otp": "src/components/forms/input-otp.tsx",
    "components/forms/native-select": "src/components/forms/native-select.tsx",
    "components/forms/radio-group": "src/components/forms/radio-group.tsx",
    "components/forms/select": "src/components/forms/select.tsx",
    "components/forms/slider": "src/components/forms/slider.tsx",
    "components/forms/switch": "src/components/forms/switch.tsx",
    "components/forms/toggle": "src/components/forms/toggle.tsx",
    "components/forms/toggle-group": "src/components/forms/toggle-group.tsx",
    "components/layout/accordion": "src/components/layout/accordion.tsx",
    "components/layout/aspect-ratio": "src/components/layout/aspect-ratio.tsx",
    "components/layout/button-group": "src/components/layout/button-group.tsx",
    "components/layout/card": "src/components/layout/card.tsx",
    "components/layout/carousel": "src/components/layout/carousel.tsx",
    "components/layout/collapsible": "src/components/layout/collapsible.tsx",
    "components/layout/item": "src/components/layout/item.tsx",
    "components/layout/resizable": "src/components/layout/resizable.tsx",
    "components/layout/scroll-area": "src/components/layout/scroll-area.tsx",
    "components/navigation/breadcrumb": "src/components/navigation/breadcrumb.tsx",
    "components/navigation/command": "src/components/navigation/command.tsx",
    "components/navigation/menubar": "src/components/navigation/menubar.tsx",
    "components/navigation/navigation-menu":
      "src/components/navigation/navigation-menu.tsx",
    "components/navigation/pagination":
      "src/components/navigation/pagination.tsx",
    "components/navigation/sidebar": "src/components/navigation/sidebar.tsx",
    "components/navigation/tabs": "src/components/navigation/tabs.tsx",
    "components/overlays/alert-dialog":
      "src/components/overlays/alert-dialog.tsx",
    "components/overlays/context-menu":
      "src/components/overlays/context-menu.tsx",
    "components/overlays/dialog": "src/components/overlays/dialog.tsx",
    "components/overlays/drawer": "src/components/overlays/drawer.tsx",
    "components/overlays/dropdown-menu":
      "src/components/overlays/dropdown-menu.tsx",
    "components/overlays/hover-card":
      "src/components/overlays/hover-card.tsx",
    "components/overlays/popover": "src/components/overlays/popover.tsx",
    "components/overlays/sheet": "src/components/overlays/sheet.tsx",
    "components/overlays/tooltip": "src/components/overlays/tooltip.tsx",
    "components/primitives/button": "src/components/primitives/button.tsx",
    "components/primitives/checkbox": "src/components/primitives/checkbox.tsx",
    "components/primitives/direction": "src/components/primitives/direction.tsx",
    "components/primitives/input": "src/components/primitives/input.tsx",
    "components/primitives/label": "src/components/primitives/label.tsx",
    "components/primitives/separator": "src/components/primitives/separator.tsx",
    "components/primitives/textarea": "src/components/primitives/textarea.tsx",
    "lib/utils": "src/lib/utils.ts",
  },
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  external: ["react", "react-dom", "next"],
  minify: false,
})
