import { defineConfig } from "tsup"

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "components/badge": "src/components/badge.ts",
    "components/button": "src/components/button.ts",
    "components/card": "src/components/card.ts",
    "components/checkbox": "src/components/checkbox.ts",
    "components/dialog": "src/components/dialog.ts",
    "components/dropdown-menu": "src/components/dropdown-menu.ts",
    "components/input": "src/components/input.ts",
    "components/label": "src/components/label.ts",
    "components/popover": "src/components/popover.ts",
    "components/radio-group": "src/components/radio-group.ts",
    "components/select": "src/components/select.ts",
    "components/sheet": "src/components/sheet.ts",
    "components/skeleton": "src/components/skeleton.ts",
    "components/sonner": "src/components/sonner.ts",
    "components/switch": "src/components/switch.ts",
    "components/table": "src/components/table.ts",
    "components/tabs": "src/components/tabs.ts",
    "components/textarea": "src/components/textarea.ts",
    "components/tooltip": "src/components/tooltip.ts",
    "components/display/badge": "src/components/display/badge.tsx",
    "components/display/skeleton": "src/components/display/skeleton.tsx",
    "components/display/table": "src/components/display/table.tsx",
    "components/feedback/sonner": "src/components/feedback/sonner.tsx",
    "components/forms/radio-group": "src/components/forms/radio-group.tsx",
    "components/forms/select": "src/components/forms/select.tsx",
    "components/forms/switch": "src/components/forms/switch.tsx",
    "components/layout/card": "src/components/layout/card.tsx",
    "components/navigation/tabs": "src/components/navigation/tabs.tsx",
    "components/overlays/dialog": "src/components/overlays/dialog.tsx",
    "components/overlays/dropdown-menu":
      "src/components/overlays/dropdown-menu.tsx",
    "components/overlays/popover": "src/components/overlays/popover.tsx",
    "components/overlays/sheet": "src/components/overlays/sheet.tsx",
    "components/overlays/tooltip": "src/components/overlays/tooltip.tsx",
    "components/primitives/button": "src/components/primitives/button.tsx",
    "components/primitives/checkbox": "src/components/primitives/checkbox.tsx",
    "components/primitives/input": "src/components/primitives/input.tsx",
    "components/primitives/label": "src/components/primitives/label.tsx",
    "components/primitives/textarea": "src/components/primitives/textarea.tsx",
    "lib/utils": "src/lib/utils.ts",
  },
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  external: ["react", "react-dom", "next"],
  minify: false,
})
